### ISSUE TITLE
Feature Req: "--desktop" option: Icon View on X Background

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#100]
```pcmanfm( or pcmanfm-qt) --desktop``` command can be used to expose ~/Desktop
as X background. It allows management of those files similar to "icon view". Thunar,
nautilus, kde/dolphin, etc provides similar functionality too.

Personally, I do not use any specific desktop environment. I use only X, openbox,
xfce4-panel and pcmanfm-qt as a very lightweight desktop on VoidLinux.

Today, I've played with qtfm and concluded that I would switch to it if it provides similar functionality. qtfm is much leaner than any of the above alternatives.

Is it possible to have "--desktop" option?

**Comment by rodlie** [comment]
This is something I have/had planned, but also something that will take time and also depends on other open issues before I can even start working on this feature.

**Comment by imrn** [comment]
https://github.com/IgnorantGuru/spacefm

spacefm also has "--desktop" option. In my opinion
it is one of the snappiest fm out there. (especially for
desktop mode). Unfortunately, its development seems
out-of steam.

It's not polished and distilled for an instant intuitive user
experience. But, once you're done your customizations
and get used to it it has many useful functionalities.

I'm not encouraging qtfm to mimic spacefm. However,
many of it's ideas can be used if they can be implemented
in simple and lean terms.

**Comment by rodlie** [comment]
Been looking at X11, screens, workspace etc and in my opinion this should be handled by a dedicated app.

At the moment qtfm is not suitable to be used as a "desktop". It can in the future (when I finally get the time to re-write the main GUI for v7), but as-is this is a no-go. Also, adding proper desktop-support will requires a lot of code not related to file management.

I do however have an alternative solution, https://github.com/rodlie/draco-desktop.

I forked Lumina some time ago with the goal of making a simple and clean DE (can also be used as a standalone desktop+panel), I should have something usable by the end of the month. The DE will integrate against/require other projects I'm working on (qtfm, powerkit etc).

**Comment by imrn** [comment]
> Been looking at X11, screens, workspace etc and in my opinion this should
> be handled by a dedicated app.
> 
> At the moment qtfm is not suitable to be used as a "desktop". It can in the
> future (when I finally get the time to re-write the main GUI for v7), but as-is this
> is a no-go. Also, adding proper desktop-support will requires a lot of code not
> related to file management.

Of, course. What I mean by "managing desktop" is just
"Files Icon View on X background". Nothing more 
than that. I'm now using qtfm as my main fm. Desktop handling
is done via "spacefm --desktop". I'd like to have them unified.
What would be the ETA of such an narrowed down feature?

> I do however have an alternative solution, https://github.com/rodlie/draco-desktop.
> 
> I forked Lumina some time ago with the goal of making a simple and clean DE
> (can also be used as a standalone desktop+panel), I should have something
> usable by the end of the month. The DE will integrate against/require other
> projects I'm working on (qtfm, powerkit etc).

I'd like to see it grow as a set of loosely coupled set of apps, playing
nicely with each other. But they should also run perfectly when used alone.

Two such functionality/app can be defined narrowly:
- Panel: Application menus/launcher/taskbar/etc.. That is only an
application/window handling thing.
- Multi Display Management: I use xfce4-display-settings which allows
convenient physical placement of displays. Of, course I'd expect panel and
desktop handling fm to be compatible with multihead configurations.

My understanding of "desktop" is nothing more than that.
No to eyecaddy things. Just black background. It is beautiful. ;)

**Comment by rodlie** [comment]
close as development regarding this has moved to https://github.com/rodlie/draco-desktop
