### ISSUE TITLE
"Settings" Dialog opens in 15 secs (v6.1.5)

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#101]
This is for my lean VoidLinux system with a 2 core 1.66Hz Intel Atom cpu.
It is not the fastest machine on earth but good enough for everyday tasks of browsing,
word processing etc. Firefox opens in 4-5 secs.

**Comment by rodlie** [comment]
This is a know issue, settings does a lot of stuff during init and slow CPUs (pre-core2) do suffer from this.

I have already done several performance improvement to settings, but not enough if seems.

**Comment by rodlie** [comment]
Not able to test this in my computer (thinkpad x220, dual core i5), settings takes under 1sec to launch, but I do have a "first-gen" 1.6ghz atom laptop somewhere, will install qtfm and test on that.

**Comment by rodlie** [comment]
Fixed in master.

The issues was that the mime database was loaded during dialog startup, it will now only load when you select "mime settings" in the settings dialog.

**Comment by imrn** [comment]
Thank you.
