### ISSUE TITLE
Settings -> Mime Types are unsorted

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#102]
It's difficult to find the mimetype I'm looking for.

**Comment by imrn** [comment]
How about something like "show matches as you type"?

**Comment by rodlie** [comment]
I will need to look at the code and see what I can do, also note that this may impact #101 more.

**Comment by rodlie** [comment]
Added to master (6.2.0).

I just added a line edit where you can filter mime types.

**Comment by imrn** [comment]
Thanks.
