### ISSUE TITLE
Discussion: C++, qt

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#107]
Qt is still the viable library to use. However, it has a of 25-30 years baggage with old c++ style.

C++ feels like a new language today and it seems the trend is accelerating with new proposals pouring in:

http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2018/
http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2019/

Committee work is slow. But distilation process of a language/library with such a broad base is inherently a slow thing. Even, I'd call it "fast" looking at the latest additions.

One of them is "FileSystem" library on C++.
https://en.cppreference.com/w/cpp/experimental/fs

I'd suggest using it whenever possible instead of qt components.

There are also proposals for a C++ standard UI. But it is still very far away.

I also have concerns about incorporating "qt" within the name of project components.

**Comment by rodlie** [comment]
I will always use what is provided with Qt first, as this is a Qt-based project. Also note that qtfm is not bleeding edge.

I have not problem with the "qt" in "qtfm", it's a file manager using Qt ;) (and this will not change).
