### ISSUE TITLE
Fantasy: Filemanager/desktop implemented using a game engine

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#108]
How about managing files/desktop in an experimental environment similar
to minecraft or something more advanced?

Or are there any other fantastic views? ;)

Did you recognize that 30+ years old term of "desktop" is loosing its
meaning in such a setup?

**Comment by rodlie** [comment]
"Exotic" file managers already exists. qtfm is a traditional file manager.

Note that the only reason I maintain qtfm is that once or twice a week I need to drag and drop something in an application, the rest of the time I use a terminal :)
