### ISSUE TITLE
Dangerous: Deleting Bookmark, deletes underlying directory

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#109]
It will be good to overhaul "Bookmark Management".

**Comment by rodlie** [comment]
Unable to replicate.

**Comment by imrn** [comment]
Details:
1- Create a folder
2- Create a bookmark for it
3- Go to bookmarks pane
4- Right click on the new bookmark.
5a- Selecting "Delete" Brings up a dialog: "Warning: You are about to delete _path_"
Confirmation certainly DELETES the _path_. But invalid bookmark stays there.
Note, that user is expecting to delete the "bookmark" only. That's why it is dangerous.
5b- Select "Move Trash". _path_ itself is moved to trash. Invalid Bookmark continues to
stay there.

**Comment by imrn** [comment]
There is no way I can really delete the "Bookmark" itself other than
going to config file and deleting it there.

**Comment by rodlie** [comment]
6.1.6 added tab completion, but it broke the context menu for bookmarks. 6.1.7/master fixes this.

**Comment by rodlie** [comment]
latest build from 6.1 branch: https://github.com/rodlie/qtfm/releases/download/6.1.7-rc1/qtfm-6.1.7-rc1-Linux64.tgz
