### ISSUE TITLE
/.config/mimeapps.list as default or option

### ISSUE THREAD

**Issue by AcarBurak** [rodlie/qtfm#113]
According to [Arch Wiki](https://wiki.archlinux.org/index.php/XDG_MIME_Applications#mimeapps.list), ~/.local/share/applications/mimeapps.list (as well as the defaults.list) is deprecated. So I've been using ~/.config/mimeapps.list. It would be good to have it here:

Settings > Mime Types > Configuration file: > /.config/mimeapps.list

**Comment by rodlie** [comment]
I'm a bit unsure about changing the default (deprecated does not mean it's not used), but will of course add an option for ~/.config/mimeapps.list

**Comment by AcarBurak** [comment]
Sure, as an option would be enough. Thank you.

**Comment by rodlie** [comment]
added in master, please test if possible.

**Comment by AcarBurak** [comment]
Works. Thank you again.
