### ISSUE TITLE
New Tab button on toolbar

### ISSUE THREAD

**Issue by AcarBurak** [rodlie/qtfm#115]
would be fine, as it's needed frequently. … Well, in fact, a configurable toolbar would still be nicer or at least some other buttons for changing views (icons, thumbs. hidden etc.)

**Comment by rodlie** [comment]
yeah, we had a bunch of icons in the toolbar, but I removed what I considered (at that time) as "bloat".

qtfm includes a lot of legacy code that needs to be changed, mainly the main GUI and tabs. I have started work on a new UI to fix old code (v7), but qtfm is currently not my highest priority so it will take some time.

**Comment by rodlie** [comment]
added an option to show "new tab" in toolbar. 

A better toolbar (with more options) will be added in the future.

**Comment by AcarBurak** [comment]
Thank you.

**Comment by rodlie** [comment]
Didn't see your last comment, will check.

**Comment by rodlie** [comment]
Yeah, "open tab" only works if the path is a dir. Will set to home dir if empty.
