### ISSUE TITLE
Unable to run applications from partitions mounted with the "user" mount option.

### ISSUE THREAD

**Issue by Wobblystep** [rodlie/qtfm#120]
The file system is Ext4.
I'm the owner of the application file and it's marked as executable and using Run from the context menu doesn't do anything, and pressing enter opens it as a text file.

The reason I'm bringing this up is because it works in Thunar, but I'm not sure which behavior is more desired.

(I'm doing the mounting that way to make it more convenient for unmounting)

**Comment by rodlie** [comment]
Will check later today.

Please add any additional information that may be helpful (mount commands etc).

**Comment by rodlie** [comment]
Not able to replicate at this moment.

Is the partition mounted with ``exec``? Adding the ``user`` flag will enable ``noexec``. Other than that I don't know, if the file is executable (and the permissions are ok) it should work.

**Comment by Wobblystep** [comment]
Actually, i have retried with nofail,x-gvfs-show,user,exec,dev,suid and it's still not running the executable.
im using gnome-disks in Fedora 29.

It is mounted in a subdirectory like this: /home/username/subdir
Filesystem type auto.
I have tried with and without the "Require additional authorization to mount" option.

**Comment by Wobblystep** [comment]
Got it to work. the path had a space in the middle of the name, so i guess that's the bug.
Sorry for the confusion, stopped testing and just assumed stuff.

**Comment by rodlie** [comment]
Good. Will find and fix the path bug.

**Comment by rodlie** [comment]
Please download and test : https://github.com/rodlie/qtfm/archive/0eda4d147394d548059052e8616f1692221e8e12.tar.gz

or use git (6.1 branch).

**Comment by Wobblystep** [comment]
Have tested that source code and it works.
Tyvm.
I do have another thing that is hard to replicate, but will use the file manager more and maybe something will make it more obvious.
Navigate up sometimes doesn't work :) some other day will post a new issue.

Have a good one!

**Comment by rodlie** [comment]
Will check the navigation for bugs. I sadly don't use qtfm as much as I should (I use the terminal for file stuff), so I don't catch as many bugs as I should.

Please report any issues (small or large) and I will do my best to fix them.
