### ISSUE TITLE
Request: "Open in new tab" right click context menu item

### ISSUE THREAD

**Issue by imrn** [rodlie/qtfm#124]
Requested functionality:

1) Right click on a directory displayed in right panel.
2) Click on "Open in new tab"  on context menu.
3) New tab is opened at the background.

**Comment by rodlie** [comment]
You can middle click a folder to open in new tab, is context menu needed?

**Comment by rodlie** [comment]
added anyway, I also found and fixed a related bug when adding the feature, win, win.

**Comment by imrn** [comment]
Of course, it is not needed. It is also saves an extra click.
I'm obviously open to such better alternatives for this and
other request/issues. Thank for pointing it out.

**Comment by rodlie** [comment]
some touchpads has dodgy middle-click, so "open in new tab" might be needed on some configurations, thanks for requesting the issue.

**Comment by imrn** [comment]
Infact, I'm not a fan of crowded context menus which
create cognitive and mouse movement loads.
Ideally ability for customization may be the solution.
It may be an overkill or may be not.
Lets think about it together with custom actions.
May be we can think of optionally removing
items from the menu.

**Comment by rodlie** [comment]
the "open in new tab" action replaced "open" for folders, so we didn't add more bloat, but I get your point.

Making major changes to the context menu is for v7, where I'm currently doing the main UI from scratch, while keeping as much of the old code as possible.

**Comment by imrn** [comment]
On 3/21/19, rodlie <notifications@github.com> wrote:
> some touchpads has dodgy middle-click, so "open in new tab" might be needed
> on some configurations, thanks for requesting the issue.

:) Thanks a lot for thanking for the issue.
That's not a typical developer behaviour
nowadays. Thanks for providing such a practical
tool.

**Comment by imrn** [comment]
Flexibity of context menu is invaluable for the power user.
Lets have special attention/issue as it evolves.
I'm sure we will have such points for the desktop environment too.
