### ISSUE TITLE
Question regarding lib

### ISSUE THREAD

**Issue by jubalh** [rodlie/qtfm#137]
Just a friendly reminder :-)

Seems like you intend to put some code in a lib soon.
Looks like you would name it libfm, if I'm not mistaken. Are you aware that there is already a lib with that name? There is [libfm](https://github.com/lxde/libfm/) and [libfm-qt](https://github.com/lxqt/libfm-qt).

**Comment by rodlie** [comment]
The library in 6.2+ is called libQtFM and the default (release) build option is static. If you build as debug then it will default to shared library.

You can enable shared library in release build with ``CONFIG+=sharedlib``

**Comment by jubalh** [comment]
Great. Thanks!
