### ISSUE TITLE
No default application for mime: application/vnd.appimage!

### ISSUE THREAD

**Issue by probonopd** [rodlie/qtfm#138]
Getting

> No default application for mime: application/vnd.appimage!

when double-clicking an AppImage file which has the executable bit set.

![default](https://user-images.githubusercontent.com/2480569/57429124-a6859800-721a-11e9-9d1d-00d480cfbacd.png)

**Comment by rodlie** [comment]
Will fix.

**Comment by rodlie** [comment]
Done in 6.2 and master

**Comment by probonopd** [comment]
Thank you very much.
