### ISSUE TITLE
version bump outside of version release, is this intentional?

### ISSUE THREAD

**Issue by jhelfman** [rodlie/qtfm#156]
I see where this has happened in the code, however after building the latest commit, the version notes that it is 6.3.0, yet there hasn't been a release for that version.

I am the maintainer of the FreeBSD port. I have 6.2.0, and the latest commit is 91 commits ahead of the release, as noted on the homepage for qtfm. So when I went to build 6.2.0.91, the version displayed is 6.3.0.

I was wondering what versioning scheme is used outside of tagging releases?

Thanks.

**Comment by rodlie** [comment]
The master branch is always the next (unreleased) version. When master is stable enough it will be branched out as 6.3 and (that branch) get patch releases if needed until the the next master is branched again (as 6.4) repeat ...

6.2.0 is currently the latest stable, 6.3.0 will be released next month.

**Comment by jhelfman** [comment]
Oh, ok. I didn't know if you created a branch and then merged to master... Thanks for explaining the release process.
