### ISSUE TITLE
Feature Request: Volume mounter/explorer

### ISSUE THREAD

**Issue by LuxLucian** [rodlie/qtfm#173]
Would adding a list of volumes/drives or a way to quickly mount them and open be doable? Without the menu I have no idea how to mount and explore the drives inside of qtfm without an external tool.

**Comment by CarDGee** [comment]
I was also looking for this feature, with it qtfm could be a great alternative to other file managers.

**Comment by rodlie** [comment]
qtfm supports volumes in the left sidebar and a dedicated app qtfm-tray. What more do you need?

**Comment by LuxLucian** [comment]
Can you quickly mount and explore external and internal drives or do you need to mount them via command line and bookmark the location to explore them? I just installed qtfm again and I don't see anything referring to my two other internal drives in the sidebar.

**Comment by rodlie** [comment]
"it just works" if you have the required service running (UDisks2).

**Comment by CarDGee** [comment]
O

> qtfm supports volumes in the left sidebar and a dedicated app qtfm-tray. What more do you need?

Perhaps to be working "out of the box" apparently I am not the only one with the same issue and instead of trying to figure why, you seem to be a bit irritated, you can close this issue as i have lost interest. Sorry to bother you mate.
Btw i had udisks running.

**Comment by rodlie** [comment]
qtfm supports uDisks2, if you have problems it's not in qtfm.

![qtfm-drives](https://user-images.githubusercontent.com/34516798/119939929-d2ede780-bf8e-11eb-819f-a57665de8e23.png)
