### ISSUE TITLE
Fails to launch associated application

### ISSUE THREAD

**Issue by anilsg** [rodlie/qtfm#21]
When double clicking a txt file associated with gvim, or right clicking and selecting open with gvim, nothing happens (expect the file to open in gvim). When selecting open with Libre Office you can see the Libre Office splash screen flicker into view but then nothing else happens. Open with xfw appears to work. Open with vim doesn't respond either. 
Linux carbon 4.16.12-1-ARCH #1 SMP PREEMPT Fri May 25 23:30:31 UTC 2018 x86_64 GNU/Linux
If you can tell me where to find logs or get debug output I'll see if I can help.

**Comment by rodlie** [comment]
Thanks for the report, will check at bit later today. What desktop/wm are
you using?

**Comment by anilsg** [comment]
I'm using openbox, but I think I've just found out why. I ran qtfm from the console and then attempted operation: 
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:50:25)
Unknown option argument: "-f /home/anil/foo/bar/baz.txt"
More info with: "vim -h"

**Comment by rodlie** [comment]
Thanks for the additional information. Seems like the associated .desktop
file is parsed wrong, will debug.

**Comment by anilsg** [comment]
I hope I've not configured something wrong. I'm not too sure if my desktop / mime types etc is set up properly. If you can tell me where it's looking for .desktop etc. I can investigate as well.

**Comment by rodlie** [comment]
I don't think you have configured anything wrong. The .desktop files on Arch are i /usr/share/applications.

When I open something with gvim I also get the "vim" error, looking at the .desktop file I see the Exec is "gvim -f %f", this is correct, but for some reason it looks like vim.desktop (with Exec "vim %F") is used when executing the command.

**Comment by rodlie** [comment]
Think I have fixed it, will commit a fix you can try a bit later.

**Comment by rodlie** [comment]
Please test the master branch when you get the time:

```
git clone https://github.com/rodlie/qtfm
cd qtfm
git submodule update --init --recursive
mkdir build && cd build
qmake .. && make -j4
./fm/qtfm
```

**Comment by rodlie** [comment]
This is a blocker for 6.0.0 Final, and it (now) works for me. So I will close this issue.

Please do test, and if it still don't work re-open this issue.

**Comment by anilsg** [comment]
It works, rodlie, thanks very much.
Are you going to release 6.1.0?
I'd like to see this come through the Archlinux pacman package,
but I guess I can just overwrite the binary for now.

**Comment by rodlie** [comment]
You have the latest package? https://aur.archlinux.org/cgit/aur.git/commit/?h=qtfm&id=52bac459f3fc1be85f1745ddf555825b9a984448

``pacman -Q --info qtfm``

**Comment by anilsg** [comment]
I didn't pull from git, I downloaded from AUR.
I'll do a git pull and rebuild.
This is what I've got now:
$ pacman -Q --info qtfm
Name            : qtfm
Version         : 6.0.0_beta1-2
Description     : A lightweight file manager
Architecture    : x86_64
URL             : https://github.com/rodlie/qtfm/releases
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : qt5-base
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 826.00 KiB
Packager        : Anil Gulati <anilg@users.sourceforge.net>
Build Date      : Sun 27 May 2018 22:28:45 AEST
Install Date    : Sun 27 May 2018 22:30:16 AEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

**Comment by rodlie** [comment]
As you can see you are running 6.0.0 Beta 1. Upgrade to final and your issue is resolved.

**Comment by anilsg** [comment]
Thanks Rodlie, I didn't expect the AUR to be updated so quickly.
I've rebuilt the AUR and my issue is resolved.
Thank you.
