### ISSUE TITLE
samba support

### ISSUE THREAD

**Issue by rodlie** [rodlie/qtfm#3]

**Comment by rodlie** [comment]
Network support in a file manager is almost a must-have. Note that I have not even started planing the implementation, so it's currently just an suggestion.

**Comment by rodlie** [comment]
I would rather develop a plugin system, that way it's easier for distributions to package the application.

You have /usr/lib*/qtfm/*.so with various plugins, and a ui in settings to enable/disable the plugins?

**Comment by rodlie** [comment]
But for now I can add options to enable/disable existing features.

**Comment by 0pLuS0** [comment]
Yeah, whatever works for you, I was just throwing ideas out there.

I just know that people that compile source like the option to disable at compile time to remove feature/options not needed, and keep the bloat down.

So I guess then, if this is a Plugin System, then some README about the Plugin System, explaining what these options are, and then maybe if someone doesn't even need this Plugin System, and option to disable it...

```--disable-plugins```

:+1:

**Comment by 0pLuS0** [comment]
Sweet!

Oh yeah, stupid me, this isn't gtk with --disable-option... :)

But can someone disable/enable these individually?

CONFIG+= yes_udisks  ?
CONFIG+= yes_dbus  ?

udisks & dbus will probably commonly used...

What is the ```open``` one?

**Comment by rodlie** [comment]
As default everything is enabled, you just disable what you don't want.

If you disable dbus then the application will not enable the dbus session and disable power features. If you disable udisks then the application will not be aware of storages and qtfm-tray will not work.

```open``` is qtfm-open, an application launcher for Openbox/Fluxbox etc.

**Comment by 0pLuS0** [comment]
Ok, I switched over to the Master branch now...

Thanks

**Comment by rodlie** [comment]
Close...

Maybe add something in the future, but for now I would rather concentrate one core functions.
