### ISSUE TITLE
Master: Various Settings Changed - Hidden Files Appear 

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#32]
Hi,

I noticed when I make a settings change under 'General, and save, then the hidden files appear...

I've haven't tried this in the other sections.

**Comment by rodlie** [comment]
Will check, I was doing several changes last month to master related to settings, I'm not done yet.

**Comment by 0pLuS0** [comment]
Ok, sorry if I'm jumping here on all these issues...

**Comment by rodlie** [comment]
No problem, tt will remind me to actually do it ;)

The problem here is that in 5.x when you hit save everything in config was reloaded, not good. I have fixed most of the issues related to settings in master, but a couple of small issue remain (probably everything related to the file view).

**Comment by rodlie** [comment]
Long story short-ish: I needed a file manager not tied to a desktop, The best I found was QtFM. I first found v5.5 on qtfm.org, but it was abandoned and had some issues, then I found out that it was further maintained by another person until v5.9. That version was a bit better, but had a lot of bugs, so I just started fixing them, then added stuff I needed. 

I have not heard anything from the original maintainers, so I just started maintaining it under the same name. If for some reason they do contact me and have issues with me maintaining it I will apply and rename the project.

**Comment by 0pLuS0** [comment]
Yeah keeping the name should be fine, you just keep the original Authors listed like as I mentioned before in the AUTHORS file.

I'm glad to see this going again, Linux needs a really nice stable light weight file manager.

**Comment by rodlie** [comment]
regarding the issue.

The hidden option should not be in settings, as it's available in view. So removing it from settings should fix this issue.

**Comment by 0pLuS0** [comment]
Sorry for any confusion, I was not saying there was a Hidden Option in the Settings.

I was saying, that if I change any Options in the Settings, then the Hidden files appear as soon as I click Save...

**Comment by rodlie** [comment]
And the reason for this has to do with the settings :) Will fix it.
