### ISSUE TITLE
Request: Various Items - Wish

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#33]
Hi,

So here's my request wish list.

1. When showing hidden files can you make them just appear in normal color, not greyed out?
2. Single Click option needed.
3. Change Bookmarks & Folder sizes

If I think of anymore I'll add them here.

Thank you for your time and consideration! :+1: 

------------------------------------

```New Options```

The Title name QtFM - Changes to a Directory name, but since there is already /path next to the Home icon, I'd leave the title always displaying the name QtFM.

Please allow in the Settings an Option for the /path to not keep a History, so that it can only be used to search /paths, but no history is being kept. The /path showing /home/foo below;

![path](https://user-images.githubusercontent.com/36190223/42424984-6c2a1fc8-8305-11e8-90d9-50187746cb30.jpg)

```For the /path section, if you need me to file a bug report, please let me know, because if you go to a /path several times, it adds that in, so you see the same /paths over like as example;```

/home/foo/
/opt/game
/home/foo
/usr/lib
/
/boot/
/boot/grub
/boot
/boot/grub
/
/home/foo

**Comment by rodlie** [comment]
1. Colors are on my todo, I will make them optional
2. Single click is an undocumented feature in 6.0, in 6.1 they are in the settings.
```
singleClick=1		single click activation of directories only
singleClick=2		everything is single click
```
3. Should be doable

**Comment by 0pLuS0** [comment]
1. optional - ahh good.
2. Sorry, I should see a setting? Because I don't...
3. Great

Oh, on a side not of just ```Cosmetics``` in the ```About``` section, you name has a tilde above the letter A?

~
A

Also the date 5.2018 has a dash - after it, ```5.2018-```, but nothing there, so don't need the dash for now.

If Michal and Wittfella are no longer active, you don't need them in the ```About``` section, just add them to a AUTHORS file, shows as previous...

**Comment by rodlie** [comment]
2:
![qtfm-sclick](https://user-images.githubusercontent.com/34516798/42416565-8fef36c0-8272-11e8-8cd7-19344b77d148.png)

I don't see any text issues in the about dialog:
![qtfm-about](https://user-images.githubusercontent.com/34516798/42416573-d427b9e8-8272-11e8-86ff-c007e444f14b.png)

Regarding the about dialog, I just added myself to the list. I would prefer not to have it (less code).

**Comment by 0pLuS0** [comment]
Hmm that explains it, I don't have the ```Default

**Comment by 0pLuS0** [comment]
Don't remove the ```About``` LOL, this is very common to see in an application...

Here I made it look different, as an example for you...


![about](https://user-images.githubusercontent.com/36190223/42416896-f978bebc-8269-11e8-999b-2fcce6a3ceef.jpg)

**Comment by rodlie** [comment]
I will re-add a new one.

**Comment by 0pLuS0** [comment]
Ok on colors...

Did you notice I'm missing in the Settings > ```General Behavior```

**Comment by rodlie** [comment]
Are you running master?

**Comment by 0pLuS0** [comment]
No you had me on another branch before, I just switched, so I'll let you know...

Thanks

**Comment by rodlie** [comment]
Ok, the 6.0 branch will only get critical fixes, the master branch is 6.1, eta end of this month.

**Comment by 0pLuS0** [comment]
ok...

6.1 is looking nice, now I see all these changes.... LOL

In 6.1 is this correct to always see this at start?

 ~ >qtfm
mime type "inode/directory" "/" 

Then when I close I always get a lot of output;

mime type "text/plain" "/home/foo/Downloads/merlin" 
search mime icon "text/plain" "Papirus" 
mime type "text/plain" "/home/rog/Downloads/merlin" 
search mime icon "text/plain" "Papirus" 

The first time I ran qtfm the output was about 3x more then this...

Maybe nice to have this silenced, and not displayed in the terminal.

**Comment by 0pLuS0** [comment]
1. I compiled it as ```CONFIG+=release``` It appears, that I only see a lot of output when closing qtfm for the first time. Now, when I close qtfm, the second time, this is all I see at the terminal;

```~ >qtfm 
mime type "inode/directory" "/"``` 

2. Colors ok...

3. Hmm, I can't say I've ever seen a file manager having a fallback icon theme. Every DE, Gnome, KDE, Xfce, etc., has icon themes installed by default, and anyone tweaking by hand a small WM like Openbox will set up their own icons. I'm still don't believe this is needed, it's up to the end-user to ensure they have icons installed and setup...

4. qtf-open, sounds good...

5. qtfm-tray, ok...

6. Don't forget ```Use Dark theme``` All DE, Gnome, KDE, Xfce, etc., have themes, and small WM, the end-users set them up. I don't see a need for this, just more trouble for you, and it's not working correct for me, around all the icons it appears in white...

**Comment by rodlie** [comment]
1: Will double check debug output. Regarding README etc, the files are not loaded multiple times, the mimetype check is running. Will check if they are running more that they should.

3: Please explain how you can set a icon theme for Qt without a theme engine.

Remember QtFM is a desktop independent application, so it need to work without a DE.

**Comment by rodlie** [comment]
Just one more thing, I might have missed several issues from you, since I don't get any notification when you edit posts.

**Comment by rodlie** [comment]
> The Title name QtFM - Changes to a Directory name, but since there is already /path next to the Home icon, I'd leave the title always displaying the name QtFM.

What if I have several windows open and want to switch to a specific window? Then I need the path in the title.

I can of course add a setting where you can remove path from title.

**Comment by 0pLuS0** [comment]
Ok on the mimetype...

Distros come with theme engines, this is why you don't have to add any support in the file manager.

Now this ```Desktop Independent``` you speak of, I'm not sure what the advantage/disadvantage is, but since this is a GUI app, everyone is going to run qtfm under a DE or WM, which will supply everything needed...

You said' ```What if I have several windows open and want to switch to a specific window?```

You mean if you have several windows open and you want to then switch to a ```specific path?```

As far as the /path section is concerned, I mention before if you could make it keeping a History of the /paths as an option. Sorry for any confusion, I didn't mean to get rid of this ability, but just an Option for those that want to enable/disable it...

Thank you... :+1:

**Comment by rodlie** [comment]
You can't expect users to manually setup a compatible theme engine just to get qtfm working when running a WM. qtfm should work out-of-the-box as long as the required dependencies are installed, not requiring additional actions from the user to get it working.

Icon theme works as following in qtfm:

 * 1. if there is an existing theme (not hi-color) use that (you are running a DE/WM with a theme engine)
 * 2. Check gtk2 config for icon theme
 * 3. Check gtk3 config for icon theme
 * 4. Check for fallbacks in XDG_PATHS/share/icons:
   * adwaita
   * tango
   * gnome
   * oxygen
   * fail! no icons for you

The first "hit" will be saved for later use when 1 don't work. You can override the fallback icon in settings.


I will look into the history stuff.

**Comment by rodlie** [comment]
Please review this thread and let me know if there is something I forgot.

**Comment by 0pLuS0** [comment]
I'm still not following this theme engine conversation.

My understanding, looking at qtfm, or any qt application for Linux is no different, meaning, qtfm doesn't require any special theme engines to work. The typical theme engines that already come with KDE and Gnome, and which people develop for work.

So I'm still lost, as to why you add in themes and icons, when these already come in desktop environments. And anyone that is going to run GUI applications under even the smallest of Window Managers is going to need themes/theme engines, and icons installed for them...

The only way I understand this, is if someone was running some small WM, and qtfm was the only GUI app they were using, then I see the need here...

This reply; ```The first "hit" will be saved for later``` are you talking about the /path history? So if someone was in their HOME, then went to / now they are still going to see?

/home/foo
/

We left of the ```Title``` reguest I mentioned, leaving the name QtFM in the title, because for now it just shows folder names is all, not /complete/paths. Also if you want the title to eventually display /paths, maybe you can make this an Option for uses to enable/disable in the settings;

```Settings``` > ```Title Paths```

**Comment by rodlie** [comment]
I don't use a theme engine, and I know a lot that also don't use one.

If I disable icon theme fallback then qtfm will look like this in a WM:
![qtfm-hicolor](https://user-images.githubusercontent.com/34516798/42480155-51d6ef52-83dc-11e8-99da-14a68e589005.png)

The applications I use don't require a theme engine to function, so why should qtfm require one? I would go so far as to say that any application that requires a theme engine to function is badly designed.

I really don't understand why this is a big deal, it's a tiny feature that improves the user experience.

**Comment by 0pLuS0** [comment]
Your screen shot is showing no ```Icons```. Icons are not related to a ```Theme Engine```

Here on SlackBuilds is the gtk-engine; aks theme engine(s)

https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445

Your screen shows qftm using a theme, which looks like ```Clear Looks```, so there is a theme engine installed, otherwise qtfm would end up looking like an old TLC/TK application.

Sorry, so now what are we talking about themes, or icons?

Every GUI application in Linux is supported by theme engines and requires them to run. Now I'm not a QT developer like you, so, compared to GTK apps, QT apps might be more inclined to having themselves self-contained for theme support, but I have never seen this before in Linux to be honest, and I've been running Slack since the 7.0x release, and I've used a lot of QT apps.

Please don't misunderstand me, again I am on your side to help and support you, the issue is that there's no need for this, because you clearly have a theme running on your box, being displayed as I mentioned ```Clear Looks```. The only thing you are missing are icons.

Try to think about it like this, how many people using Linux are only going to run one GUI application, and this is QtFM? If this is true, then I can see this need, otherwise, for all the GUI apps everyone typically uses, theme engines and icons are installed in the system by default.

The only reason I am saying to drop this, is to just have less code and things to worry about, because as QT & GTK standards change, and we all know how that breaks things, you might have to maintain this code to keep up with QT, so it doesn't break...

I hope I have made myself clearer now...

Thanks

**Comment by 0pLuS0** [comment]
Your showing no icons, I've always understood in Linux we have two types of Eye Candy, as I call it... :)

icon theme set
theme engine

My understanding is an ```icon theme set```, is not the ```theme-engine``` Maybe some confusion on the terminology here.

Somewhere a long, I got lost, thinking of ```Themes``` because you have the ```Use Dark Theme``` option, which I also mentioned to remove.

The only reason I am saying to drop the ```Use Dark Theme``` & ```Fallback Icon theme```, to keep the code simpler for you to maintain. I'd assume in the future as QT and GTK continue to change, these will be things you have to also maintain.

I hope I have made myself clearer now...

Thanks

**Comment by rodlie** [comment]
On Tue, Jul 10, 2018 at 3:54 AM, 0pLuS0 <notifications@github.com> wrote:

> Your screen shot is showing no Icons. Icons are not related to a Theme
> Engine
>
> Here on SlackBuilds is the gtk-engine; aks theme engine(s)
>
> https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-
> systemless-t3473445
>
> Your screen shows qftm using a theme, which looks like Clear Looks, so
> there is a theme engine installed, otherwise qtfm would end up looking like
> an old TLC/TK application.
>
Icons are set by the engine, either during the session, or saved as a
config file in gtk etc. If no theme engine is running then the application
is on it own, and need to handle icons manually somehow.

I use no theme engine, remember Qt includes various styles (either set in
qtconfig or in app, or theme). Qt5 for examples uses Fusion as default
(what's in the screenshot).

> Sorry, so now what are we talking about themes, or icons?
>
Every GUI application in Linux is supported by theme engines and requires
> them to run. Now I'm not a QT developer like you, so, compared to GTK apps,
> QT apps might be more inclined to having themselves self-contained for
> theme support, but I have never seen this before in Linux to be honest, and
> I've been running Slack since the 7.0x release, and I've used a lot of QT
> apps.
>
> Please don't misunderstand me, again I am on your side to help and support
> you, the issue is that there's no need for this, because you clearly have a
> theme running on your box, being displayed as I mentioned Clear Looks.
> The only thing you are missing are icons.
>
Try to think about it like this, how many people using Linux are only going
> to run one GUI application, and this is QtFM? If this is true, then I can
> see this need, otherwise, for all the GUI apps everyone typically uses,
> theme engines and icons are installed in the system by default.
>
You can install as many engines and icons you will, the application will
still need to know what icons to use, if no theme engine is running then
the application don't have a icon theme to use, and then need to provide a
fallback.

> The only reason I am saying to drop this, is to just have less code and
> things to worry about, because as QT & GTK standards change, and we all
> know how that breaks things, you might have to maintain this code to keep
> up with QT, so it doesn't break...
>
I have described the process of finding fallback icons earlier in this
thread, it's not something that will break in the future (well, never say
never, but the code is simple).

**Comment by rodlie** [comment]
On Tue, Jul 10, 2018 at 4:23 AM, 0pLuS0 <notifications@github.com> wrote:

> Your showing no icons, I've always understood in Linux we have two types
> of Eye Candy, as I call it... :)
>
> icon theme set
> theme engine
>
> My understanding is an icon theme set, is not the theme-engine Maybe some
> confusion on the terminology here.
>
The engine takes care of the style, font and icons.

> Somewhere a long, I got lost, thinking of Themes because you have the Use
> Dark Theme option, which I also mentioned to remove.
>
"Dark mode" qtfm is just a palette ,
https://github.com/rodlie/qtfm/blob/master/libfm/common.h#L494

**Comment by rodlie** [comment]
Made an example of how icon themes work qt:
[qtfindicon.tar.gz](https://github.com/rodlie/qtfm/files/2180328/qtfindicon.tar.gz)
qmake&&make&&./qtfindicon

This will show you what Qt found as default theme, if empty or hicolor then you have no icons and need to provide a fallback.


Also. "normal" applications don't have to think about this, they have a more or less a predefined set of icons they use, and provide a bundled fallback icon if the theme can't provide one. A file manager is more complicated in this regard, and needs a complete icon-theme to function properly.

**Comment by 0pLuS0** [comment]
Oh sorry, I pasted a XDA link I was looking at when I made the reply, instead of to slackbuilds.org

Ok I read everything you mentioned, and sorry for dragging this on for so long... :face_with_head_bandage: 

I was only trying to help, since icons and themes are in distros, and for the geeks, well they're not hard to get and install...

I was hoping to save you some pain, well hopefully there won't be any...

Thanks

**Comment by rodlie** [comment]
No problem. qtfm has a more "complicated" fallback system for icons than others, but for a reason. File managers that is part of a DE don't have to think about this, since they can always assume the DE is running and takes care of stuff like icons etc. I can't assume that. 

It's the same with XDG, I need access to several XDG variables, but they are normally not available when running a WM, so I also have to do some fallback work there as well.

The next time I may need to edit the icon code is when gtk4 comes out (since I parse the gtk configs and they have different names/locations).

**Comment by 0pLuS0** [comment]
Oh wait, need to unzip the lips! LOL

Why did you close this? I mentioned I made a new section at the original post;

```New Options```

So I can make any future requests... hmm

**Comment by rodlie** [comment]
Just create new issues (easier to follow).

**Comment by 0pLuS0** [comment]
Ok thanks...

**Comment by 0pLuS0** [comment]
Sorry, I forgot to ask, in the latest master the mime output was removed/fixed? Because I don't see anything at the terminal anymore... :)

**Comment by rodlie** [comment]
master should not display any debug output if built with ``CONFIG+=release``.
