### ISSUE TITLE
Clicking Bookmarks Doesn't Change /path

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#35]
Hi,

I noticed now that you fixed the Bookmark icons, that when clicking on the default bookmarks;

Computer - Home - Desktop - Trash

qtfm doesn't change to these /paths now...

Clicking them does nothing...

**Comment by rodlie** [comment]
Will check.

**Comment by rodlie** [comment]
Fixed in master and 6.0.

Will do a 6.0.2 release a bit later.

**Comment by rodlie** [comment]
Note you must remove bookmarks from config since the values stored are wrong.

**Comment by rodlie** [comment]
I will release 6.0.2 later tonight (it's 04:51 Sunday morning here), so if you find anything broken please report.

**Comment by 0pLuS0** [comment]
Ok will do! :+1:
