### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by psikoz** [rodlie/qtfm#36]
Hey @rodlie 

![qtfm](https://user-images.githubusercontent.com/40601249/42417914-b27e2176-829d-11e8-87d2-1da00f0b929e.jpg)

I created a logo by combining the qt logos and the file icon. I think this logo will be very elegant in the readme file. that's how it will look; WDYT?

![qtfm](https://user-images.githubusercontent.com/40601249/42417916-bb9c0390-829d-11e8-84ea-ed2d883f9758.png)

**Comment by rodlie** [comment]
Nice, I like the idea.

What about this:
![logov2](https://user-images.githubusercontent.com/34516798/42418030-a8045bda-8297-11e8-877b-fdf76e6ba203.jpg)
A bit simpler.

**Comment by psikoz** [comment]
wow super :)  After making the changes, I'm sending a pr. What do you say?

**Comment by 0pLuS0** [comment]
No offense, but looks to much like it's from the Official QT Project...

Need something original... :)

**Comment by rodlie** [comment]
Maybe a different color will help? :)

![logov3](https://user-images.githubusercontent.com/34516798/42418256-9af0110a-829c-11e8-98e6-1eabef95fbaa.jpg)

I don't have time to make one myself, so it's up to the community.

**Comment by psikoz** [comment]
I actually wanted to emphasize qt. You want something independent of QT? @0pLuS0

**Comment by 0pLuS0** [comment]
Well it is a QT application, so in that manner of speaking it's not independent of QT.

Just better to make an original logo that doesn't look like it came from the QT project is all I meant...

**Comment by psikoz** [comment]
I designed new logos. how are these?

![qtfm](https://user-images.githubusercontent.com/40601249/42418848-cb7ec784-82b1-11e8-87d0-63d9471404b3.jpg)

**Comment by rodlie** [comment]
Much better :)

**Comment by rodlie** [comment]
I think I would prefer yellow/orange, the Q could be used for header/promo stuff, and the "plain" folder as the main icon?

![untitled](https://user-images.githubusercontent.com/34516798/42419196-371fe9de-82b0-11e8-93d2-7da258fd768a.png)

I also liked the other icon....... hard to make up my mind, need input from others :)

**Comment by 0pLuS0** [comment]
Yeah these are looking better! :+1:

**Comment by 0pLuS0** [comment]
@rodlie yes that is a nice look, might make people think you'e Irish... LOL

Maybe a different color hehe :)

**Comment by psikoz** [comment]
ofcourse, I used almost all the colors :) Which one should I send a pr for?

![qt](https://user-images.githubusercontent.com/40601249/42631701-a8e7f152-85e3-11e8-9c25-1b1537b2aa4f.jpg)

**Comment by 0pLuS0** [comment]
Well now actually since this is a QT app, I think that second row green next to the purple is quite a nice shade... 👍

**Comment by psikoz** [comment]
Okay, i sent a pull-request. I hope you like it.

**Comment by rodlie** [comment]
Thanks :+1: 

I will keep this issue open since I need to integrate the logo into the app and website.

**Comment by rodlie** [comment]
The new logo has been integrated, closing issue.

**Comment by 0pLuS0** [comment]
Yeah look nice @rodlie 

By the way, since I know you're hacking away on the Master, I won't open a new issue, but when I've made some changes in the settings, I get this all back at the terminal;


 ~ >qtfm 
link outline hasn't been detected!
link outline hasn't been detected!
link outline hasn't been detected!
libpng warning: iCCP: known incorrect sRGB profile

**Comment by rodlie** [comment]
libpng warnings can be ignored, just means one (or more) png somewhere don't have correct color profile. Will double check that the png's bundled with qtfm is not the issue.

Fonts are aligned in the center here (qt4/qt5), screenshot? And if that is the case then it's related to #34

**Comment by 0pLuS0** [comment]
Come to think of it, I'm using at the moment the Faenza icons, and they are a bit old, so they are probably the issue now that I think about it...

So I'll run this on them and see how it goes;

```cd /path
find . -type f -name "*.png" -exec convert {} -strip {} \;```

I've attached a screen shot, all the directories labels are aligned to the left, some are more noticeable then others... But if you look close at the ones that aren't as noticeable, you'll see too, they are also off a little. Just stare long and hard... LOL 



![qtfm](https://user-images.githubusercontent.com/36190223/42805078-6022c4c8-899a-11e8-89b3-e8bede2b4e0a.jpg)

**Comment by rodlie** [comment]
> I've attached a screen shot, all the directories labels are aligned to the left, some are more noticeable then others... But if you look close at the ones that aren't as noticeable, you'll see too, they are also off a little. Just stare long and hard... LOL

Yeah, it's not perfect, the text is aligned to the center, but I added some offset padding to avoid some other issue and that it probably the reason for the text being off by some pixels on some text.

**Comment by rodlie** [comment]
> link outline hasn't been detected!

This is a warning related to SVG, so probably a broken-ish SVG somewhere (icon theme or .desktop). If you rebuild in debug mode you should see the filename.

I get this warning on ``qt.svg``, probably used by one of the .desktop files included with qt/qt-creator.

**Comment by 0pLuS0** [comment]
I compiled it ```CONFIG+=debug``` but when I ran qtfm it didn't tell me what icon is causing the ```libpng warning: iCCP: known incorrect sRGB profile``` message.

Sorry I got lost now, if you are saying on your last reply, ```This is a warning related to SVG```, I thought this only applies to a ```PNG```?

I'm wondering, with the PNG that come in the source, when they get compiled in, if this is somehow changing them then?

**Comment by rodlie** [comment]
Only the SVG warning (link outline) displays the filename (and only in qt5).

I can check the included PNGs.
