### ISSUE TITLE
qtfm-6.0.2/libdisks/libdisks.pro

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#37]
Hi,

I just grabbed the 6.0.2 release to check it out, and /libdisks/libdisks.pro is missing...

**Comment by rodlie** [comment]
6.0.x uses submodules. The tar.xz in releases include the submodules.

**Comment by rodlie** [comment]
And just to avoid confusion, 6.1 does not use submodules anymore.

**Comment by 0pLuS0** [comment]
I assumed the two source code downloads would be the same, that's actually confusing having 3, the top comes across to me more like a precompiled binary download, and if you want, source below... 

I grabbed the;
https://github.com/rodlie/qtfm/archive/6.0.3.tar.gz

**Comment by rodlie** [comment]
I can't do anything about the tar.gz and zip downloads, they will always be there. For 6.0.x you must download the **tar.xz** because I used submodules and they are not included in the zip and tar.gz generated by github, in 6.1+ this will not be needed anymore since I don't use submodules anymore.

**Comment by 0pLuS0** [comment]
By the way, I just compiled this, and now I see pictures and archives with green text. Did you do this?

![qtfm_text](https://user-images.githubusercontent.com/36190223/42720002-2b3f26da-870f-11e8-85dc-42697b3365ba.jpg)

**Comment by rodlie** [comment]
colors are optional in 6.1

**Comment by 0pLuS0** [comment]
Sorry what do you mean about the tar.gz and zip downloads, they will always be there? GitHub is generating these for you?

**Comment by 0pLuS0** [comment]
Ok on colors, I didn't recall seeing them before, looks odd... 

Thanks

**Comment by rodlie** [comment]
the **tar.gz** and **zip** file on the release page is generated by github, so they will always be there, and since I used submodules in 6.0 the generated archives are without the required submodules, that's why I also have to release a **tar.xz**. Anyway, this will be resolved when 6.1 is final, then you can just use the tar.gz/zip generated by github.

Yeah, the colors are a bit funky, I prefer plain colors. But it's the default from the 5.x series. I will make text colors default off in 6.1.

**Comment by 0pLuS0** [comment]
All sounds good! :+1:

**Comment by 0pLuS0** [comment]
MAN is now in the HOUSE! LOL

./
install/
install/slack-desc
install/doinst.sh
usr/
usr/doc/
usr/doc/qtfm-6.1.0/
usr/doc/qtfm-6.1.0/LICENSE
usr/doc/qtfm-6.1.0/README.md
usr/doc/qtfm-6.1.0/AUTHORS
```usr/man/
usr/man/man8/
usr/man/man8/qtfm.8.gz```
usr/bin/
usr/bin/qtfm
usr/share/
usr/share/applications/
usr/share/applications/qtfm.desktop

Slackware package /tmp/qtfm-6.1.0-x86_64-1_foo.tgz created.

**Comment by rodlie** [comment]
added a (git) SlackBuild to master, you can just run that from the folder every time you update.

```
git pull
sudo ./qtfm.SlackBuild
sudo upgradepkg /tmp/qtfm-VERSION.tgz
```

**Comment by 0pLuS0** [comment]
Hey now, I'm a Proud Slacker Geek, don't take away all my fun, I have to make my own .SlackBuilds LOL... ;)

THANKS
