### ISSUE TITLE
Rename & Gaps Between Directories

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#39]
Hi,

I noticed a few things in Master, that when right clicking to rename a file or directory, the entire file, folder, image, etc., is highlighted. Please change this, so only the name is highlighted in color.

Please see the attached screen shots showing how a folder and image gets highlighted with blue all around it.

Also please see the screen shot under / showing the directories and the gaps. Left - Right Gaps are ok, it's the Up - Down Gaps is to big, folders should be closer together underneath each other...

Thanks

![rename_1](https://user-images.githubusercontent.com/36190223/42720388-9fa140f2-8715-11e8-8b87-db19fac08718.jpg)

![rename_2](https://user-images.githubusercontent.com/36190223/42720389-a3f3d8a4-8715-11e8-9181-e1f088b9879a.jpg)

![gaps](https://user-images.githubusercontent.com/36190223/42720391-a871dda4-8715-11e8-8af9-24d27f47c186.jpg)

**Comment by 0pLuS0** [comment]
This is how the space/gaps Up & Down should look instead;


![gaps_2](https://user-images.githubusercontent.com/36190223/42720411-14a25954-8716-11e8-9f23-1b2cf22e76fb.jpg)

**Comment by rodlie** [comment]
This is issue #34 and should be discussed there instead. I added the functionality, but it's not perfect, will be fixed.

**Comment by 0pLuS0** [comment]
Long names are effecting the Gaps?
