### ISSUE TITLE
Enhance "open with" to open multiple selected files

### ISSUE THREAD

**Issue by anilsg** [rodlie/qtfm#40]
I can create a custom action to open multiple selected files like "gvim %f" but this doesn't work with the normal open. If I select two files and open with gvim only one file is opened. Can open with be updated to open multiple files too?

**Comment by rodlie** [comment]
Will look into this, if the changes are minor then I will add it to 6.1, else it will have to wait until 6.1 is done.

**Comment by rodlie** [comment]
Ok, so have been looking into how to solve this and it should be doable for 6.1.

I will first implement this in "Open". The current implementation takes every files marked and open them individually using the preferred application.

I will:

* get all selected files
* get mime types for selected files
* get app for each mime type
* if some of the mime types have same app, merge them
* for each mime type open default app:
  * if default app support ``%F`` then add all files for mime type, else open a new instance for each file

Sound ok? Need to think a bit more about how to solve the "open with ..." menu.

**Comment by rodlie** [comment]
btw, the "open" command supports multiple files, it just don't support apps that supports multiple files, so marking several files and right-click and select "open" will open the selected files, but "open with.." only supports one file.

I have a working implementation for multiple files in one app using the "open" command.

**Comment by rodlie** [comment]
This has been fixed in the master branch. 

"open", "open with ...", "select" now supports multiple files. qtfm also checks if the application supports multiple files, so you won't get multiple instances of the app (if it supports multiple files that is).

Please test the feature and re-open this issue if something don't work or I broke something else.

**Comment by anilsg** [comment]
Yes, sorry about the working I'm sending you, rodlie, and thanks for your fast responses. I didn't stop long enough to consider the ramifications.

As you say, to support this feature you absolutely need to know if the application supports multiple files. I can't see how qtfm is told whether an application can handle multiple files.

I pulled from GitHub, built and installed with makepkg (Arch) and Help > About now says QtFM 6.0.3

I tested with mupdf which opens PDF etc but only one file at a time, and gvim, which opens multiple files simultaneously:

- "Open" multiple PDFs launches as many mupdf instances as needed, one per file. Great!
- "Open With" mupdf multiple PDFs only opens the one under the cursor.
- "Open" multiple text files launches as many gvim instances, with one buffer / file per window.
- "Open With" gvim multiple text file again only opens the one under the cursor.
- My "gvim %f" custom action works great, opening all selected files in one instance of gvim with multiple buffers. Fantastic!
- "Open" multiple mixed type files does great for PDFs, opening all pdfs in separate instances of mupdf as required, but gvim again uses multiple instances instead of one. It's great that the right applications are fed the right files, though, and they're all opened.

Just mix it up some more, opening a file name with spaces in the name:

- "Open" and "Open With" a single file gets treated as two files so "foo bar.txt" is opened as "foo" and "bar.txt". Gvim gets both of these 'files' in one window but of course they're bogus. The real file is not opened. mupdf can't open anything this way.
- My "gvim %f" action works great, opening the specified file regardless of spaces in the filename.
- When opening multiple files with spaces the behaviour is consistent with previous descriptions. Each original selected file launches an instance, but the spaces again are treated as separators and multiple bogus file names are handed to each application instance.
![shot](https://user-images.githubusercontent.com/23533709/42762529-f02715c0-8953-11e8-8d9b-5427745a3bd9.jpg)

**Comment by anilsg** [comment]
Come to think of it, would you consider, when pasting copies of a file, instead of "Copy (n) of <originalname>", how about something systemically suitable like "<originalname>-YYYYMMDD.HHMM" or "<originalname>-copy-YYYYMMDD.HHMM" if you think including "copy" is needed, or for some users you may want "<originalbasename>-YYYYMMDD-HHMM.<originalext>"?

This sorts the copies right next to the originals, and also provides the right kind of marker when creating backup copies during system management. Did I mention how much I love qtfm? It's the best file manager, no other is better. :-)

**Comment by anilsg** [comment]
@rodlie I can't re-open this issue because I didn't close it. If nothing happens for a few days I'll create a new issue, and replicate the late comments. No worries.

**Comment by rodlie** [comment]
> I pulled from GitHub, built and installed with makepkg (Arch) and Help > About now says QtFM 6.0.3

That don't sound right, should be 6.1.0.

Do a git clone from the master branch and just built it manually. I can give you instructions if wanted.

You can also try a static build I made:
[qtfm-fdeadef-static-linux64.zip](https://github.com/rodlie/qtfm/files/2198911/qtfm-fdeadef-static-linux64.zip)

The issues you have sounds like 6.0.x.

**Comment by rodlie** [comment]
> Come to think of it, would you consider, when pasting copies of a file, instead of "Copy (n) of ", how about something systemically suitable like "<originalname>-YYYYMMDD.HHMM" or "<originalname>-copy-YYYYMMDD.HHMM" if you think including "copy" is needed, or for some users you may want "<originalbasename>-YYYYMMDD-HHMM.<originalext>"?

I could add a setting for how the copy should be named?

**Comment by rodlie** [comment]
Ok, I don't know how AUR git works. The PKGBUILD tracks stable as far as I know.

Great that is works, marking issue as resolved.
