### ISSUE TITLE
Copy(x) of: Custom filename

### ISSUE THREAD

**Issue by rodlie** [rodlie/qtfm#42]
> Come to think of it, would you consider, when pasting copies of a file, instead of "Copy (n) of ", how about something systemically suitable like "-YYYYMMDD.HHMM" or "-copy-YYYYMMDD.HHMM" if you think including "copy" is needed, or for some users you may want "-YYYYMMDD-HHM

https://github.com/rodlie/qtfm/issues/40#issuecomment-405258061

My suggestion:

Add a lineedit in settings where the user can customize the filename.

**Comment by rodlie** [comment]
So...

A line edit with default ``Copy (%1) of %2`` where you can make your own with the following options:
```
%1 = num copy
%2 = orig filename (example.tar.gz)
%3 = timestamp (yyyyMMddHHmmss)
%4 = orig suffix (example.tar.gz=>tar.gz)
%5 = orig basename (example.tar.gz=>example)
```

Does that sound ok @anilsg?

**Comment by rodlie** [comment]
Added to master, please test.

**Comment by anilsg** [comment]
Are you joking that would be fantastic.
Just a tiny suggestion:
yyyyMMdd-HHmmss is slightly more readable, slightly closer to ISO.
Also someone may want to split date and time if they just want the date for instance.
Presumably all other characters are taken literally.
Don't waste your time escaping '%' no-one should have that in their file name anyway.

**Comment by rodlie** [comment]
I will also add support for custom timestamp ;)

**Comment by rodlie** [comment]
Yeah, I should move this to 'advanced' in settings, as it shouldn't be on the front page in settings.

**Comment by anilsg** [comment]
That's great rodlie, thanks heaps!
Now you've made it possible for users to screw things up ;-)
I configure custom copy destination %2-%3 and set timestamp to yyyyMMdd-HHmm
Now I copy and paste a file.
Now I paste it again immediately (before a minute rolls over)
That means I'm trying to paste a file of the same name
There's a pause where nothing happens
Then a dialog box comes up initializing ...

**Comment by rodlie** [comment]
Will test.

**Comment by rodlie** [comment]
> I configure custom copy destination %2-%3 and set timestamp to yyyyMMdd-HHmm

I configured the app with the same settings, copy/paste 3 files:
![copyx](https://user-images.githubusercontent.com/34516798/42957485-21743d84-8b83-11e8-92bc-2a42f997b5c2.png)

Looks ok here.

debug:
```
DESTNAME ORIG "applicationdialog.o"
DESTNAME FILTER "%2-%3" "yyyyMMdd-HHmm"
DESTNAME RESULT "applicationdialog.o-20180719-1841"
```

**Comment by rodlie** [comment]
Didn't read your post properly, able to replicate the issue.

**Comment by rodlie** [comment]
Should be fixed in master.

**Comment by anilsg** [comment]
Confirmed the fix works great. Pasting a second copy with a configured name that is the same as the first copy, recurses the copy-naming, which is a logical and helpful solution. Thanks again.
