### ISSUE TITLE
Selected options get blanked

### ISSUE THREAD

**Issue by anilsg** [rodlie/qtfm#44]
Hi Rodlie, I really hope this is just my install or something like that. I was using the Archlinux AUR package but since that is now only 1.0.3 I've started building from your Github master in order to test recent additions to 6.1.0. I find that when selecting certain navigation options such as directories in the bookmarks list or different option sections in preferences, the label gets blanked when selected. See screenshot.
![shot](https://user-images.githubusercontent.com/23533709/43038336-e20f6fe0-8d5a-11e8-893f-1ee17df9891b.jpg)

**Comment by rodlie** [comment]
Seems like a qt/theme/color "issue". I don't think I changed anything related to theme/color but will check.

Workaround is to select "dark mode" in appearance.

**Comment by rodlie** [comment]
fixed in master, was introduced when I made some style sheet changes in qt5, I probably ran "dark mode" or something that overrode the default theme so I didn't notice (and this was only related to qt5).
