### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by cdwijs** [rodlie/qtfm#45]
Hi all, When I compile, I see the following:|
`10:29:31: Running steps for project qtfm...
10:29:31: Starting: "C:\Qt\5.11.1\mingw53_32\bin\qmake.exe" "E:\memories\2018 git\qtfm\qtfm.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
Info: creating stash file E:\memories\2018 git\build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug\.qmake.stash
10:29:31: The process "C:\Qt\5.11.1\mingw53_32\bin\qmake.exe" exited normally.
10:29:31: Starting: "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" qmake_all
cd libfm\ && C:\Qt\5.11.1\mingw53_32\bin\qmake.exe -o Makefile "E:\memories\2018 git\qtfm\libfm\libfm.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd libfm\ && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
mingw32-make[1]: Entering directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libfm'
mingw32-make[1]: Nothing to be done for 'qmake_all'.
mingw32-make[1]: Leaving directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libfm'
cd libdisks\ && C:\Qt\5.11.1\mingw53_32\bin\qmake.exe -o Makefile "E:\memories\2018 git\qtfm\libdisks\libdisks.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd libdisks\ && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
mingw32-make[1]: Entering directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libdisks'
mingw32-make[1]: Nothing to be done for 'qmake_all'.
mingw32-make[1]: Leaving directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libdisks'
cd fm\ && C:\Qt\5.11.1\mingw53_32\bin\qmake.exe -o Makefile "E:\memories\2018 git\qtfm\fm\fm.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd fm\ && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
mingw32-make[1]: Entering directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/fm'
mingw32-make[1]: Nothing to be done for 'qmake_all'.
mingw32-make[1]: Leaving directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/fm'
cd tray\ && C:\Qt\5.11.1\mingw53_32\bin\qmake.exe -o Makefile "E:\memories\2018 git\qtfm\tray\tray.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd tray\ && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
mingw32-make[1]: Entering directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/tray'
mingw32-make[1]: Nothing to be done for 'qmake_all'.
mingw32-make[1]: Leaving directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/tray'
10:29:38: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited normally.
10:29:38: Starting: "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" 
cd libfm\ && ( if not exist Makefile C:\Qt\5.11.1\mingw53_32\bin\qmake.exe -o Makefile "E:\memories\2018 git\qtfm\libfm\libfm.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libfm'
C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libfm'
g++ -c -fno-keep-inline-dllexport -g -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I..\..\qtfm\libfm -I. -IC:\Qt\5.11.1\mingw53_32\include -IC:\Qt\5.11.1\mingw53_32\include\QtWidgets -IC:\Qt\5.11.1\mingw53_32\include\QtGui -IC:\Qt\5.11.1\mingw53_32\include\QtANGLE -IC:\Qt\5.11.1\mingw53_32\include\QtDBus -IC:\Qt\5.11.1\mingw53_32\include\QtCore -Idebug -IC:\Qt\5.11.1\mingw53_32\mkspecs\win32-g++  -o debug\desktopfile.o ..\..\qtfm\libfm\desktopfile.cpp
g++ -c -fno-keep-inline-dllexport -g -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I..\..\qtfm\libfm -I. -IC:\Qt\5.11.1\mingw53_32\include -IC:\Qt\5.11.1\mingw53_32\include\QtWidgets -IC:\Qt\5.11.1\mingw53_32\include\QtGui -IC:\Qt\5.11.1\mingw53_32\include\QtANGLE -IC:\Qt\5.11.1\mingw53_32\include\QtDBus -IC:\Qt\5.11.1\mingw53_32\include\QtCore -Idebug -IC:\Qt\5.11.1\mingw53_32\mkspecs\win32-g++  -o debug\fileutils.o ..\..\qtfm\libfm\fileutils.cpp
..\..\qtfm\libfm\fileutils.cpp:3:21: fatal error: sys/vfs.h: No such file or directory
compilation terminated.
Makefile.Debug:1028: recipe for target 'debug/fileutils.o' failed
mingw32-make[2]: Leaving directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libfm'
mingw32-make[2]: *** [debug/fileutils.o] Error 1
Makefile:36: recipe for target 'debug' failed
mingw32-make[1]: Leaving directory 'E:/memories/2018 git/build-qtfm-Desktop_Qt_5_11_1_MinGW_32bit-Debug/libfm'
mingw32-make[1]: *** [debug] Error 2
Makefile:43: recipe for target 'sub-libfm-make_first' failed
mingw32-make: *** [sub-libfm-make_first] Error 2
10:29:42: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project qtfm (kit: Desktop Qt 5.11.1 MinGW 32bit)
When executing step "Make"
10:29:42: Elapsed time: 00:11.`

My versions:
Qt 5.11.1 Mingw 5.3 32 bit
windows 7 profesional SP1

Cheers,
Cedric

**Comment by rodlie** [comment]
Windows is not supported. Sorry about that.

I could of course make qtfm build-able on Windows, but you would end up with a worse alternative than what's included in Windows, so I don't see the point.
