### ISSUE TITLE
Add fallback for QIcon::fromTheme (check for valid icon)

### ISSUE THREAD

**Issue by 0pLuS0** [rodlie/qtfm#49]
Hi,

I just noticed for some odd reason, that the Aw0Ken icon set appears with all the folder and file icons very tiny... hmm

https://www.deviantart.com/alecive/art/AwOken-163570862

```Aw0ken - small size```

![qtfm_1](https://user-images.githubusercontent.com/36190223/43107110-0f0fae9e-8ecb-11e8-83b1-5b69a3d14011.jpg)

```Faenza - normal size```

![qtfm_2](https://user-images.githubusercontent.com/36190223/43107138-28914dbe-8ecb-11e8-8b98-1a2f57613a86.jpg)

**Comment by rodlie** [comment]
Because the icon theme is broken (not installed properly).  Only some of the sizes has enough icons, so that's why you get small icons (folder icon is only available in 22x22/24x24 and 128x128).

**Comment by 0pLuS0** [comment]
Yes I understand, these sizes, but I've also used this iconset in around 3-5 distros and about 3-5 filemanagers, all the typical popular ones over the years, Dolphin, Nautilus, Nemo, PCManFM, SpaceFM, Thunar...

I'm assuming Linux Geeks know Aw0ken, here check it out on gnome-look;

https://www.gnome-look.org/browse/cat/132/ord/top/

It's been like the 3rd highest rated iconset for Linux for the past 5 years.

All I can say, is I've never looked at this as a broken iconset, and I've never heard anything about that, I've used it for 5 years since it's been around.

**Comment by 0pLuS0** [comment]
Yes I understand, these sizes, but I've also used this iconset in around 3-5 distros and about 3-5 filemanagers, all the typical popular ones over the years, Dolphin, Nautilus, Nemo, PCManFM, SpaceFM, Thunar...

I'm assuming Linux Geeks know Aw0ken, here check it out on gnome-look;

https://www.gnome-look.org/browse/cat/132/ord/top/

It's been like the 3rd highest rated iconset for Linux for the past 5 years.

All I can say, is I've never looked at this as a broken iconset, and I've never heard anything about that, I've used it for 5 years since it's been around.

All I can tell you, is I've seen iconsets like this before, where the directory sizes are taken and used from the 128x128 size or Scable directory and made to fit, based on the Preferences/Settings picked...

**Comment by rodlie** [comment]
There seems to be a bug somewhere (I don't even get 24px icons for Aw0ken). I checked that the code in libfm works, it finds the 128px icons. But fm does not use libfm to get mime icons, so it's probably a old bug somwhere.....

**Comment by rodlie** [comment]
Ok, so I think I know what's going on....

qtfm uses ``QIcon::fromTheme`` to get a icon from the icon theme. Since Aw0ken is "broken" then it won't work with Qt's internal function to get the icons.

I will add a fallback to manually get the icon needed when Qt fails.

**Comment by 0pLuS0** [comment]
When I used Dolphin in the past it worked, that's a QT app...

Why do you say Aw0Ken is broken? The developer at the time, was an extremely knowledgeable hacker. It doesn't make sense that the 3rd most popular iconset in Linux is broken.

If you have Dolphin, or other QT file mangers you know if, I'd be interested to see if you have it working in these too, and this is only QtFM not working.

Hmm

**Comment by rodlie** [comment]
Dolphin is a KDE app. qtfm uses [QIcon::fromTheme](http://doc.qt.io/qt-5/qicon.html#fromTheme) to get icons. If the theme follow the spec everything should work.

Also, if Aw0ken is/was popular it would be packaged as a icon theme in various distros.

I will add a fallback for QIcon, but it will not fix your problem.

**Comment by rodlie** [comment]
btw, fix for aw0ken:
```
--- index.theme.orig	2018-07-27 12:28:23.203583854 +0200
+++ index.theme	2018-07-27 12:29:15.657581604 +0200
@@ -3,7 +3,7 @@
 Comment=Awesome Token icon theme, by alecive
 Inherits=ubuntu-mono-dark,gnome,hicolor
 Example=python
-Directories=clear/128x128/emotes,clear/128x128/actions,clear/128x128/apps,clear/128x128/categories,clear/128x128/devices,clear/128x128/emblems,clear/128x128/mimetypes,clear/128x128/places,clear/128x128/status,clear/128x128/stock,clear/64x64/apps,clear/48x48/apps,clear/32x32/apps,clear/22x22/actions,clear/22x22/apps,clear/22x22/devices,clear/22x22/mimetypes,clear/22x22/status,clear/22x22/stock,clear/22x22/places,clear/24x24/emotes,clear/24x24/actions,clear/24x24/apps,clear/24x24/categories,clear/24x24/devices,clear/24x24/emblems,clear/24x24/mimetypes,clear/24x24/places,clear/24x24/status,clear/24x24/stock,clear/24x24/animations,clear/16x16/actions,clear/16x16/apps,clear/16x16/status
+Directories=clear/128x128/emotes,clear/128x128/actions,clear/128x128/apps,clear/128x128/categories,clear/128x128/devices,clear/128x128/emblems,clear/128x128/mimetypes,clear/128x128/places,clear/128x128/status,clear/128x128/stock
 
 [clear/128x128/actions]
 Size=128
@@ -55,164 +55,3 @@
 Context=Stock
 Type=scalable
 
-[clear/64x64/apps]
-Size=64
-Context=Applications
-Type=scalable
-
-[clear/48x48/apps]
-Size=48
-Context=Applications
-Type=scalable
-
-[clear/32x32/apps]
-Size=32
-Context=Applications
-Type=scalable
-
-[clear/24x24/actions]
-Size=24
-Context=Actions
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/animations]
-Size=24
-Context=Animations
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/apps]
-Size=24
-Context=Applications
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/categories]
-Size=24
-Context=Categories
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/devices]
-Size=24
-Context=Devices
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/emblems]
-Size=24
-Context=Emblems
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/emotes]
-Size=24
-Context=Emotes
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/mimetypes]
-Size=24
-Context=MimeTypes
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/places]
-Size=24
-Context=Places
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/status]
-Size=24
-Context=Status
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/24x24/stock]
-Size=24
-Context=Stock
-Type=scalable
-MinSize=1
-MaxSize=24
-
-[clear/22x22/actions]
-Size=22
-Context=Actions
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/22x22/apps]
-Size=22
-Context=Applications
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/22x22/devices]
-Size=22
-Context=Devices
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/22x22/mimetypes]
-Size=22
-Context=MimeTypes
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/22x22/places]
-Size=22
-Context=Places
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/22x22/status]
-Size=22
-Context=Status
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/22x22/stock]
-Size=22
-Context=Stock
-Type=scalable
-MinSize=1
-MaxSize=22
-
-[clear/16x16/actions]
-Size=16
-Context=Actions
-Type=scalable
-MinSize=1
-MaxSize=16
-
-[clear/16x16/apps]
-Size=16
-Context=Applications
-Type=scalable
-MinSize=1
-MaxSize=16
-
-[clear/16x16/status]
-Size=16
-Context=Status
-Type=scalable
-MinSize=1
-MaxSize=16

```

**Comment by 0pLuS0** [comment]
Hey wait, don't get me tangled up here, it's not my problem, LOL, I didn't make the iconset... :)

Keep up the great work!

**Comment by rodlie** [comment]
It's easy to fix it as you can see. The theme defines various icon sizes but does not provide the icons, if this happens then qt will go down one icon size and try to find the icon (repeat until 16x16). 

Since Aw0ken only provides icons for 128x128 and 24x24 everything between will not work as intended. So the theme maintainer should either not define icons sizes they don't support or provide proper icons or symlinks for each icon size in theme.index.

**Comment by 0pLuS0** [comment]
I understand a lot of this, just not sure why Aw0ken was like this...

Anyhow I don't really use it, I just threw this by you, in case others are this way...
