### ISSUE TITLE
Use decimal number for key in the config file, rather than hex numbers.

### ISSUE THREAD

**Issue by slackuser0xae34** [rodlie/qtfm#72]
Feature request:
For those who still prefer to use an external editor to setup the config file (a la Qtfm 5.5), the saving of numerical keys as hex numbers (QT default) is less desirable than using decimal numbers. I've attached two patched files to save the keys as decimal numbers. 

[mainwindow.zip](https://github.com/rodlie/qtfm/files/2473374/mainwindow.zip)
[settingsdialog.zip](https://github.com/rodlie/qtfm/files/2473375/settingsdialog.zip)

This is my preference, perhaps it isn't shared with others. Please use you best judgment in implementing this. 
Thanks for a nice file manager.

**Comment by rodlie** [comment]
Thanks for the request. I don't have anything against the modification, but we must not break existing config files created with 6.x.
