### ISSUE TITLE
xdg integration (Chrome)

### ISSUE THREAD

**Issue by ghost** [rodlie/qtfm#84]
Qtfm opens "/" directory when using "show in folder" option e. g. in web browser instead of opening directory containing the file. Probably related with xdg integration

**Comment by rodlie** [comment]
Works fine in Firefox here ...

```
cat /usr/share/applications/mimeinfo.cache |grep inode
inode/directory=qtfm.desktop;
```

Chome does nothing ... (I'm using Openbox).

So, not an qtfm issue as far as I can see.

**Comment by wojtek14** [comment]
Ok, indeed works fine with Firefox-based. Still the problem exist with chromium-based, with PCManFM works well. I am also using Openbox.

**Comment by rodlie** [comment]
Chrome:
```
/usr/bin/xdg-open: line 640: exo-open: command not found
```
I "fake" Xfce in Chrome because I need freedesktop support (since Chrome does not detect DE).
```
# Enables support for org.freedesktop.ScreenSaver when _not_ using kde/xfce:
export DESKTOP_SESSION=${DESKTOP_SESSION:-xfce}
export XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP:-xfce}
```
If I disable this then Chrome uses Firefox to open folders .....

**Comment by rodlie** [comment]
xdg-* and Chrome is a broken mess in my opinion. Will to some more testing...

**Comment by wojtek14** [comment]
Ok, so it seems like it's somehow Chrome problem. Thank you.

**Comment by rodlie** [comment]
fixed.
