### ISSUE TITLE
missing getFilename in -lQtFM

### ISSUE THREAD

**Issue by kubaroth** [rodlie/qtfm#94]
Looks like dynamic linking against -lQtFM is giving me the error (getFilename symbol is missing?)
`undefined reference to `myProgressDialog::getFilename()'`

To workaround it I had to change  in fm.pro:
from:
`LIBS += -L../libfm -lQtFM`
to:
`LIBS += -L../libfm ../libfm/libQtFM.a`

Any ideas why this is happening?

**Comment by rodlie** [comment]
dynamic is forced when in debug mode and static is forced in release mode.
